// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/harmony-development/legato/server/db/backends/sqlite/ent/localuser"
	"github.com/harmony-development/legato/server/db/backends/sqlite/ent/predicate"
)

// LocalUserDelete is the builder for deleting a LocalUser entity.
type LocalUserDelete struct {
	config
	hooks    []Hook
	mutation *LocalUserMutation
}

// Where adds a new predicate to the LocalUserDelete builder.
func (lud *LocalUserDelete) Where(ps ...predicate.LocalUser) *LocalUserDelete {
	lud.mutation.predicates = append(lud.mutation.predicates, ps...)
	return lud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lud *LocalUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lud.hooks) == 0 {
		affected, err = lud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LocalUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lud.mutation = mutation
			affected, err = lud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lud.hooks) - 1; i >= 0; i-- {
			mut = lud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (lud *LocalUserDelete) ExecX(ctx context.Context) int {
	n, err := lud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lud *LocalUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: localuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: localuser.FieldID,
			},
		},
	}
	if ps := lud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, lud.driver, _spec)
}

// LocalUserDeleteOne is the builder for deleting a single LocalUser entity.
type LocalUserDeleteOne struct {
	lud *LocalUserDelete
}

// Exec executes the deletion query.
func (ludo *LocalUserDeleteOne) Exec(ctx context.Context) error {
	n, err := ludo.lud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{localuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ludo *LocalUserDeleteOne) ExecX(ctx context.Context) {
	ludo.lud.ExecX(ctx)
}
