# SPDX-FileCopyrightText: 2021 Danil Korennykh <bluskript@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

run:
  skip-files:
    - ".*\\.pb\\.go"
    - ".*\\.hrpc\\.*.go"
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    # deprecated modules
    - golint
    - maligned
    - scopelint
    - interfacer
linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - api.NewError(
