# SPDX-FileCopyrightText: 2021 Danil Korennykh <bluskript@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

address: 0.0.0.0
port: 2289
postgres:
  db: harmony
  host: 127.0.0.1
  password: ""
  port: "5432"
  username: amadeus
redis:
  hosts:
    - 127.0.0.1:6379
  password: ""
private_key_path: harmony-key.pub
public_key_path: harmony-key.pem
