// Code generated by entc, DO NOT EDIT.

package filehash

const (
	// Label holds the string label denoting the filehash type in the database.
	Label = "file_hash"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldFileid holds the string denoting the fileid field in the database.
	FieldFileid = "fileid"
	// Table holds the table name of the filehash in the database.
	Table = "file_hashes"
)

// Columns holds all SQL columns for filehash fields.
var Columns = []string{
	FieldID,
	FieldHash,
	FieldFileid,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
