// Code generated by entc, DO NOT EDIT.

package entgen

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/harmony-development/legato/server/db/ent/entgen/file"
	"github.com/harmony-development/legato/server/db/ent/entgen/filehash"
)

// FileHash is the model entity for the FileHash schema.
type FileHash struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Hash holds the value of the "hash" field.
	Hash string `json:"hash,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FileHashQuery when eager-loading is set.
	Edges FileHashEdges `json:"edges"`
}

// FileHashEdges holds the relations/edges for other nodes in the graph.
type FileHashEdges struct {
	// File holds the value of the file edge.
	File *File `json:"file,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FileOrErr returns the File value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FileHashEdges) FileOrErr() (*File, error) {
	if e.loadedTypes[0] {
		if e.File == nil {
			// The edge file was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: file.Label}
		}
		return e.File, nil
	}
	return nil, &NotLoadedError{edge: "file"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FileHash) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case filehash.FieldID:
			values[i] = &sql.NullInt64{}
		case filehash.FieldHash:
			values[i] = &sql.NullString{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type FileHash", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FileHash fields.
func (fh *FileHash) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case filehash.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			fh.ID = int(value.Int64)
		case filehash.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				fh.Hash = value.String
			}
		}
	}
	return nil
}

// QueryFile queries the "file" edge of the FileHash entity.
func (fh *FileHash) QueryFile() *FileQuery {
	return (&FileHashClient{config: fh.config}).QueryFile(fh)
}

// Update returns a builder for updating this FileHash.
// Note that you need to call FileHash.Unwrap() before calling this method if this FileHash
// was returned from a transaction, and the transaction was committed or rolled back.
func (fh *FileHash) Update() *FileHashUpdateOne {
	return (&FileHashClient{config: fh.config}).UpdateOne(fh)
}

// Unwrap unwraps the FileHash entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (fh *FileHash) Unwrap() *FileHash {
	tx, ok := fh.config.driver.(*txDriver)
	if !ok {
		panic("entgen: FileHash is not a transactional entity")
	}
	fh.config.driver = tx.drv
	return fh
}

// String implements the fmt.Stringer.
func (fh *FileHash) String() string {
	var builder strings.Builder
	builder.WriteString("FileHash(")
	builder.WriteString(fmt.Sprintf("id=%v", fh.ID))
	builder.WriteString(", hash=")
	builder.WriteString(fh.Hash)
	builder.WriteByte(')')
	return builder.String()
}

// FileHashes is a parsable slice of FileHash.
type FileHashes []*FileHash

func (fh FileHashes) config(cfg config) {
	for _i := range fh {
		fh[_i].config = cfg
	}
}
