// Code generated by entc, DO NOT EDIT.

package entgen

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/harmony-development/legato/server/db/ent/entgen/filemessage"
	"github.com/harmony-development/legato/server/db/ent/entgen/predicate"
)

// FileMessageDelete is the builder for deleting a FileMessage entity.
type FileMessageDelete struct {
	config
	hooks    []Hook
	mutation *FileMessageMutation
}

// Where adds a new predicate to the FileMessageDelete builder.
func (fmd *FileMessageDelete) Where(ps ...predicate.FileMessage) *FileMessageDelete {
	fmd.mutation.predicates = append(fmd.mutation.predicates, ps...)
	return fmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fmd *FileMessageDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(fmd.hooks) == 0 {
		affected, err = fmd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FileMessageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fmd.mutation = mutation
			affected, err = fmd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fmd.hooks) - 1; i >= 0; i-- {
			mut = fmd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fmd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (fmd *FileMessageDelete) ExecX(ctx context.Context) int {
	n, err := fmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fmd *FileMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: filemessage.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: filemessage.FieldID,
			},
		},
	}
	if ps := fmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, fmd.driver, _spec)
}

// FileMessageDeleteOne is the builder for deleting a single FileMessage entity.
type FileMessageDeleteOne struct {
	fmd *FileMessageDelete
}

// Exec executes the deletion query.
func (fmdo *FileMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := fmdo.fmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{filemessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fmdo *FileMessageDeleteOne) ExecX(ctx context.Context) {
	fmdo.fmd.ExecX(ctx)
}
