// Code generated by entc, DO NOT EDIT.

package entgen

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/harmony-development/legato/server/db/ent/entgen/user"
	"github.com/harmony-development/legato/server/db/ent/entgen/usermeta"
)

// UserMetaCreate is the builder for creating a UserMeta entity.
type UserMetaCreate struct {
	config
	mutation *UserMetaMutation
	hooks    []Hook
}

// SetMeta sets the "meta" field.
func (umc *UserMetaCreate) SetMeta(s string) *UserMetaCreate {
	umc.mutation.SetMeta(s)
	return umc
}

// SetID sets the "id" field.
func (umc *UserMetaCreate) SetID(s string) *UserMetaCreate {
	umc.mutation.SetID(s)
	return umc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (umc *UserMetaCreate) SetUserID(id uint64) *UserMetaCreate {
	umc.mutation.SetUserID(id)
	return umc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (umc *UserMetaCreate) SetNillableUserID(id *uint64) *UserMetaCreate {
	if id != nil {
		umc = umc.SetUserID(*id)
	}
	return umc
}

// SetUser sets the "user" edge to the User entity.
func (umc *UserMetaCreate) SetUser(u *User) *UserMetaCreate {
	return umc.SetUserID(u.ID)
}

// Mutation returns the UserMetaMutation object of the builder.
func (umc *UserMetaCreate) Mutation() *UserMetaMutation {
	return umc.mutation
}

// Save creates the UserMeta in the database.
func (umc *UserMetaCreate) Save(ctx context.Context) (*UserMeta, error) {
	var (
		err  error
		node *UserMeta
	)
	if len(umc.hooks) == 0 {
		if err = umc.check(); err != nil {
			return nil, err
		}
		node, err = umc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMetaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = umc.check(); err != nil {
				return nil, err
			}
			umc.mutation = mutation
			node, err = umc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(umc.hooks) - 1; i >= 0; i-- {
			mut = umc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, umc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (umc *UserMetaCreate) SaveX(ctx context.Context) *UserMeta {
	v, err := umc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (umc *UserMetaCreate) check() error {
	if _, ok := umc.mutation.Meta(); !ok {
		return &ValidationError{Name: "meta", err: errors.New("entgen: missing required field \"meta\"")}
	}
	return nil
}

func (umc *UserMetaCreate) sqlSave(ctx context.Context) (*UserMeta, error) {
	_node, _spec := umc.createSpec()
	if err := sqlgraph.CreateNode(ctx, umc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}

func (umc *UserMetaCreate) createSpec() (*UserMeta, *sqlgraph.CreateSpec) {
	var (
		_node = &UserMeta{config: umc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: usermeta.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: usermeta.FieldID,
			},
		}
	)
	if id, ok := umc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := umc.mutation.Meta(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: usermeta.FieldMeta,
		})
		_node.Meta = value
	}
	if nodes := umc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usermeta.UserTable,
			Columns: []string{usermeta.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_metadata = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserMetaCreateBulk is the builder for creating many UserMeta entities in bulk.
type UserMetaCreateBulk struct {
	config
	builders []*UserMetaCreate
}

// Save creates the UserMeta entities in the database.
func (umcb *UserMetaCreateBulk) Save(ctx context.Context) ([]*UserMeta, error) {
	specs := make([]*sqlgraph.CreateSpec, len(umcb.builders))
	nodes := make([]*UserMeta, len(umcb.builders))
	mutators := make([]Mutator, len(umcb.builders))
	for i := range umcb.builders {
		func(i int, root context.Context) {
			builder := umcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMetaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, umcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, umcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, umcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (umcb *UserMetaCreateBulk) SaveX(ctx context.Context) []*UserMeta {
	v, err := umcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
