# SPDX-FileCopyrightText: 2021 Danil Korennykh <bluskript@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

address: 0.0.0.0
port: 2289
privateKeyPath: harmony-key.pub
publicKeyPath: harmony-key.pem
database:
  backend: postgres
  postgres:
    db: harmony
    host: 127.0.0.1
    password: ""
    port: 5432
    username: harmony
epheremal:
  backend: redis
  redis:
    hosts:
      - 127.0.0.1
    password: ""
debug:
  respondWithErrors: true
  logErrors: true
