// Code generated by entc, DO NOT EDIT.

package message

const (
	// Label holds the string label denoting the message type in the database.
	Label = "message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldCreatedat holds the string denoting the createdat field in the database.
	FieldCreatedat = "createdat"
	// FieldEditedat holds the string denoting the editedat field in the database.
	FieldEditedat = "editedat"
	// FieldReplyto holds the string denoting the replyto field in the database.
	FieldReplyto = "replyto"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeOverride holds the string denoting the override edge name in mutations.
	EdgeOverride = "override"
	// Table holds the table name of the message in the database.
	Table = "messages"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "messages"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_message"
	// OverrideTable is the table the holds the override relation/edge. The primary key declared below.
	OverrideTable = "message_override"
	// OverrideInverseTable is the table name for the Override entity.
	// It exists in this package in order to avoid circular dependency with the "override" package.
	OverrideInverseTable = "overrides"
)

// Columns holds all SQL columns for message fields.
var Columns = []string{
	FieldID,
	FieldAuthor,
	FieldCreatedat,
	FieldEditedat,
	FieldReplyto,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "messages"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"channel_message",
	"user_message",
}

var (
	// OverridePrimaryKey and OverrideColumn2 are the table columns denoting the
	// primary key for the override relation (M2M).
	OverridePrimaryKey = []string{"message_id", "override_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultReplyto holds the default value on creation for the "replyto" field.
	DefaultReplyto uint64
)
