# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

name: Lint legato

on: [push, pull_request]
jobs:
  golangci:
    name: Lint Legato
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
