// Code generated by entc, DO NOT EDIT.

package filemessage

const (
	// Label holds the string label denoting the filemessage type in the database.
	Label = "file_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeFile holds the string denoting the file edge name in mutations.
	EdgeFile = "file"
	// Table holds the table name of the filemessage in the database.
	Table = "file_messages"
	// FileTable is the table the holds the file relation/edge.
	FileTable = "files"
	// FileInverseTable is the table name for the File entity.
	// It exists in this package in order to avoid circular dependency with the "file" package.
	FileInverseTable = "files"
	// FileColumn is the table column denoting the file relation/edge.
	FileColumn = "file_message_file"
)

// Columns holds all SQL columns for filemessage fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
